name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-cards:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: tanzilhasan5
          BRANCH_NAME: cards-output
          UTC_OFFSET: 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
